[project]
name = "gmailctrl"
version = "0.1.0"
description = "A TUI to manage bulk email in Gmail"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual",
    "google-api-python-client",
    "google-auth-oauthlib",
]
